# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20170516_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='html_answer',
            field=models.BooleanField(default=False, help_text='Set true if the answer is in full html and does not need to have linebreaks added'),
        ),
    ]
